//scratch

SortedList.new(24).at(51); // returns nil

SortedList.new(24).inspect;


asSortedList
SortedList

(1 && 1);



true and: (false);
true and: (false);

true.and(false);
true.and(true);

(true && false);

[1,2,3,4].last;
[1,2,3,4].drop(-1);

~parent = [1,2,3,4].keep(n-1);



(
a = [1, 2, 3, 4, 5, 6, 7];
n = 5;

// Keep the first n-1 elements
b = a.keep(a.size-1);

b.postln; // This will output: [ 1, 2, 3, 4 ]
)